import React from 'react'
export const metadata = {
    title: "Analytics page",
    description: "Generated by create next app",
};
export default function Analytics() {
    return (
        <div>
            <h1 className="text-2xl">Analytics Page</h1>
        </div>
    )
}
