import React from 'react';
export const metadata = {
    title: "Settings page",
    description: "Generated by create next app",
  };
export default function Settings () {
    console.log('test');
    return (
        <div>
            <h1 className="text-2xl">Settings page</h1>
            <p className="mt-10">Lorem ipsum dolor sit amet consectetur adipisicing elit. Cumque quis commodi minus, itaque repudiandae sint expedita fuga deleniti accusantium laboriosam officia debitis aut molestias magni nobis impedit neque doloribus quam accusamus iure aspernatur labore iusto ea dolorem. At obcaecati fugit libero! Quidem suscipit repellendus ea voluptatem odio iusto magni non.</p>
        </div>
    );
}
