import Image from "next/image";
export const metadata = {
  title: "Home page",
  description: "Generated by create next app",
};
export default function Home() {
  return (
    <div className="home">
      <h className="text-2xl">Home Page</h>
      <div className="mt-10">
        This is the home page content
      </div>
    </div>
  );
}
